// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhnywsbtbmzpjbltvvkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1obnl3c2J0Ym16cGpibHR2dmtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4OTY3MTIsImV4cCI6MjA1NTQ3MjcxMn0.BKrRuFLFxn88e7pgw6HeZYTr4BlLBYzvM5QZEyJYBC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);